# Generated by Django 4.0.4 on 2022-05-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appregion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('sexe', models.TextField(max_length=50)),
                ('classification', models.TextField(max_length=500)),
            ],
        ),
    ]
