# Generated by Django 4.0.5 on 2022-06-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appregion', '0003_champ_region_alter_champ_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champ',
            name='sexe',
            field=models.CharField(max_length=50),
        ),
    ]
