# Generated by Django 4.0.5 on 2022-06-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appregion', '0004_alter_champ_sexe'),
    ]

    operations = [
        migrations.CreateModel(
            name='appli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_app', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('serveur', models.CharField(max_length=50)),
                ('utilisateur', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_service', models.CharField(max_length=200)),
                ('date_lancement', models.DateField(blank=True, null=True)),
                ('mem', models.IntegerField()),
                ('mem_vive', models.IntegerField()),
                ('serveur_lancement', models.CharField(max_length=200)),
            ],
        ),
    ]
