# Generated by Django 4.0.5 on 2022-06-13 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appregion', '0005_appli_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='appli',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='serveur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('proc', models.IntegerField()),
                ('mem', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appregion.type')),
            ],
        ),
        migrations.AlterField(
            model_name='appli',
            name='serveur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appregion.serveur'),
        ),
        migrations.AlterField(
            model_name='appli',
            name='utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appregion.utilisateur'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serveur_lancement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appregion.serveur'),
        ),
    ]
