-- MySQL Script generated by MySQL Workbench
-- Thu Jun  9 15:51:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecole
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecole
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecole` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema administration
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema administration
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `administration` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecole` ;

-- -----------------------------------------------------
-- Table `ecole`.`filiere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecole`.`filiere` (
  `IdFiliere` INT NOT NULL AUTO_INCREMENT,
  `NomFiliere` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdFiliere`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecole`.`etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecole`.`etudiant` (
  `CodeEtudiant` VARCHAR(5) NOT NULL,
  `NomEtudiant` VARCHAR(45) NOT NULL,
  `PrenomEtudiant` VARCHAR(25) NULL DEFAULT NULL,
  `DateNaissance` VARCHAR(45) NULL DEFAULT NULL,
  `VilleEtudiant` VARCHAR(45) NULL DEFAULT NULL,
  `IdFiliere` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CodeEtudiant`),
  INDEX `IdFiliere_idx` (`IdFiliere` ASC) VISIBLE,
  CONSTRAINT `IdFiliere`
    FOREIGN KEY (`IdFiliere`)
    REFERENCES `ecole`.`filiere` (`IdFiliere`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `administration` ;

-- -----------------------------------------------------
-- Table `administration`.`serveur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administration`.`serveur` (
  `idserveur` INT NOT NULL,
  `serveurNom` VARCHAR(45) NOT NULL,
  `serveurType` VARCHAR(45) NOT NULL,
  `serveurProcesseur` VARCHAR(45) NOT NULL,
  `serveurMemoire` VARCHAR(45) NOT NULL,
  `serveurStockage` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idserveur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `administration`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administration`.`utilisateurs` (
  `idutilisateurs` INT NOT NULL,
  `utilisateursNom` VARCHAR(45) NOT NULL,
  `utilisateursPrenom` VARCHAR(45) NOT NULL,
  `utilisateursemail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idutilisateurs`),
  INDEX `utilisateursNom_idx` (`utilisateursNom` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `administration`.`applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administration`.`applications` (
  `idapplications` INT NOT NULL,
  `applicationsNom` VARCHAR(45) NOT NULL,
  `applicationsLogo` VARCHAR(500) NOT NULL,
  `idServeur` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idapplications`),
  INDEX `applicationsServeur_idx` (`idServeur` ASC) VISIBLE,
  INDEX `idUtilisateur_idx` (`idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `idServeur`
    FOREIGN KEY (`idServeur`)
    REFERENCES `administration`.`serveur` (`idserveur`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUtilisateur`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `administration`.`utilisateurs` (`idutilisateurs`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `administration`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administration`.`services` (
  `idservices` INT NOT NULL,
  `servicesNom` VARCHAR(45) NOT NULL,
  `servicesdate` DATE NOT NULL,
  `servicesmemoireutilise` VARCHAR(45) NOT NULL,
  `servicesvivenecessaire` VARCHAR(45) NOT NULL,
  `idServeurlancement` INT NOT NULL,
  PRIMARY KEY (`idservices`),
  INDEX `serviceslancement_idx` (`idServeurlancement` ASC) VISIBLE,
  CONSTRAINT `idServeurlancement`
    FOREIGN KEY (`idServeurlancement`)
    REFERENCES `administration`.`serveur` (`idserveur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `administration`.`typeserveur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administration`.`typeserveur` (
  `idTypeServeur` INT NOT NULL,
  `idServeurtype` INT NOT NULL,
  `TypeServeurDescription` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTypeServeur`),
  INDEX `idServeur_idx` (`idServeurtype` ASC) VISIBLE,
  CONSTRAINT `idServeurtype`
    FOREIGN KEY (`idServeurtype`)
    REFERENCES `administration`.`serveur` (`idserveur`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `administration`.`usagedesressources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `administration`.`usagedesressources` (
  `web` VARCHAR(50) NOT NULL,
  `Db` VARCHAR(45) NULL DEFAULT NULL,
  `Stockage` VARCHAR(45) NULL DEFAULT NULL,
  `idApplication` INT NULL DEFAULT NULL,
  PRIMARY KEY (`web`),
  INDEX `idApplication_idx` (`idApplication` ASC) VISIBLE,
  CONSTRAINT `idApplication`
    FOREIGN KEY (`idApplication`)
    REFERENCES `administration`.`applications` (`idapplications`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
